openapi: 3.1.0
info:
  title: Configuration alertRules roles API
  version: 1.0.0
servers:
- url: https://test.api.solvimon.com
  description: The TEST environment for our API
- url: https://api.solvimon.com
  description: The live environment for our API
tags:
- name: roles
paths:
  /v{version}/roles:
    get:
      operationId: getRoles
      summary: Get a list of all roles
      description: Requires the ROLE.VIEW permission.
      tags:
      - roles
      parameters:
      - name: version
        in: path
        description: version
        required: true
        schema:
          type: string
          default: '1'
      - name: limit
        in: query
        description: The amount of records shown in the list
        required: false
        schema:
          type: integer
      - name: page
        in: query
        description: The page which is going to be shown
        required: false
        schema:
          type: integer
      - name: order_by
        in: query
        description: The parameter by which the response is ordered.
        required: false
        schema:
          type: string
      - name: order_direction
        in: query
        description: The order direction by which the response is ordered.
        required: false
        schema:
          type: string
      - name: name
        in: query
        description: The name of the role.
        required: false
        schema:
          type: string
      - name: include_child_roles
        in: query
        description: Returned the child roles for this role, max depth of 2 is possible.
        required: false
        schema:
          type: boolean
      - name: only_childless_roles
        in: query
        description: Return only roles that have no child roles of their own.
        required: false
        schema:
          type: boolean
      - name: X-API-KEY
        in: header
        required: true
        schema:
          type: string
      - name: x-platform-id
        in: header
        description: Platform ID.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RolePaginatedResponseWrapper'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
    post:
      operationId: postRoles
      summary: Create a role
      description: Requires the ROLE.CREATE permission.
      tags:
      - roles
      parameters:
      - name: version
        in: path
        description: version
        required: true
        schema:
          type: string
          default: '1'
      - name: X-API-KEY
        in: header
        required: true
        schema:
          type: string
      - name: x-platform-id
        in: header
        description: Platform ID.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleCreateRequest'
  /v{version}/roles/{resourceId}:
    get:
      operationId: getRolesByResourceId
      summary: Get a role
      description: Requires the ROLE.VIEW permission.
      tags:
      - roles
      parameters:
      - name: version
        in: path
        description: version
        required: true
        schema:
          type: string
          default: '1'
      - name: resourceId
        in: path
        description: The ID of the resource to be requested.
        required: true
        schema:
          type: string
          default: ''
      - name: X-API-KEY
        in: header
        required: true
        schema:
          type: string
      - name: x-platform-id
        in: header
        description: Platform ID.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
    delete:
      operationId: deleteRolesByResourceId
      summary: Delete a role
      description: Requires the ROLE.DELETE permission.
      tags:
      - roles
      parameters:
      - name: version
        in: path
        description: version
        required: true
        schema:
          type: string
          default: '1'
      - name: resourceId
        in: path
        description: The ID of the resource to be requested.
        required: true
        schema:
          type: string
          default: ''
      - name: X-API-KEY
        in: header
        required: true
        schema:
          type: string
      - name: x-platform-id
        in: header
        description: Platform ID.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
    patch:
      operationId: patchRolesByResourceId
      summary: Update a role
      description: Requires the ROLE.UPDATE permission.
      tags:
      - roles
      parameters:
      - name: version
        in: path
        description: version
        required: true
        schema:
          type: string
          default: '1'
      - name: resourceId
        in: path
        description: The ID of the resource to be requested.
        required: true
        schema:
          type: string
          default: ''
      - name: X-API-KEY
        in: header
        required: true
        schema:
          type: string
      - name: x-platform-id
        in: header
        description: Platform ID.
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RoleUpdateRequest'
components:
  schemas:
    RoleUpdateRequestChildRolesItems:
      type: object
      properties: {}
      title: RoleUpdateRequestChildRolesItems
    ApiErrorResourceType:
      type: string
      enum:
      - CUSTOMER
      - CUSTOM_FIELD
      - PLATFORM
      - PLATFORM_UPTODATE
      - METER
      - METER_VALUE
      - METER_PROPERTY
      - METER_VALUE_CALCULATION
      - INGEST_DATA
      - METER_DATA
      - CHARGE_DATA
      - PERSIST_DATA
      - ADJUSTMENT_DATA
      - PRODUCT_CATEGORY
      - PRODUCT
      - PRODUCT_ITEM
      - PRICING
      - PRICING_GROUP
      - PRICING_ITEM
      - PRICING_ITEM_CONFIG
      - PRICING_PLAN_SUBSCRIPTION
      - PRICING_PLAN_SUBSCRIPTION_GROUP
      - PRICING_PLAN_SCHEDULE
      - PRICING_PLAN
      - PRICING_PLAN_VERSION
      - QUOTE
      - QUOTE_VERSION
      - QUOTE_TEMPLATE
      - API_KEY
      - USER
      - ROLE
      - PROXY_USER
      - EXTERNAL_CREDENTIALS
      - TOKEN
      - INVOICE
      - E_INVOICE
      - PDF
      - BILLING_ENTITY
      - FEATURE
      - MEMBERSHIP
      - PAYMENT
      - PAYMENT_ACCEPTOR
      - PAYMENT_METHOD
      - PAYMENT_METHOD_OPTIONS
      - PAYMENT_SCHEDULE
      - PAYMENT_REQUEST
      - INTEGRATION
      - WEBHOOK
      - FILE
      - FILE_PROCESSING_SETTINGS
      - TEAM
      - DOWNLOAD_URL
      - CSV_REPORT
      - REPORT
      - REPORT_GENERATE_REQUEST
      - REPORT_CONFIGURATION
      - REPORT_SUBSCRIPTION
      - REPORT_DEFINITION
      - ACCOUNT_GROUP
      - ENTITY
      - EVENT_TRACE
      - EVENT_TRACE_LINK
      - PRICING_CATEGORY
      - CONTACT
      - ALERT_RULE
      - ALERT
      - AUDIT_RECORD
      - PORTAL_URL
      - AUTHENTICATION_PROVIDER
      - REPROCESS
      - APPROVAL_POLICY
      - APPROVAL_REQUEST
      - BULK_ACTION
      - COUPON
      - PROMOTION_CODE
      - WALLET
      - WALLET_TYPE
      - WALLET_GRANT
      - WORKFLOW
      - WORKFLOW_TRIGGER
      - WORKFLOW_ACTION
      - CREDIT_TYPE
      - SIGNATURE_REQUEST
      - ATTACHMENT
      - DOCUMENT
      title: ApiErrorResourceType
    RoleCreateRequest:
      type: object
      properties:
        object_type:
          type:
          - string
          - 'null'
        id:
          type:
          - string
          - 'null'
          description: Unique identifier for the role
        name:
          type: string
          description: The name of the role
        description:
          type: string
          description: The description of the role
        entity_id:
          type:
          - string
          - 'null'
          description: When present the role is created for/by this entity
        child_role_ids:
          type: array
          items:
            type: string
          description: Child roles for this role
        child_roles:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/RoleCreateRequestChildRolesItems'
          description: Child roles, with a max depth of 2
      required:
      - name
      title: RoleCreateRequest
    Role:
      type: object
      properties:
        object_type:
          type:
          - string
          - 'null'
        id:
          type:
          - string
          - 'null'
          description: Unique identifier for the role
        name:
          type: string
          description: The name of the role
        description:
          type: string
          description: The description of the role
        entity_id:
          type:
          - string
          - 'null'
          description: When present the role is created for/by this entity
        child_role_ids:
          type: array
          items:
            type: string
          description: Child roles for this role
        child_roles:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/RoleChildRolesItems'
          description: Child roles, with a max depth of 2
      title: Role
    PaginationLinks:
      type: object
      properties:
        first:
          type:
          - string
          - 'null'
        previous:
          type:
          - string
          - 'null'
        current:
          type:
          - string
          - 'null'
        next:
          type:
          - string
          - 'null'
      title: PaginationLinks
    ApiErrorCode:
      type: string
      enum:
      - RESOURCE_NOT_FOUND
      - RESOURCES_NOT_FOUND
      - UNABLE_TO_PROCESS_INSTRUCTIONS
      - BAD_REQUEST
      - UNSUPPORTED_MEDIA_TYPE
      - RESOURCE_ALREADY_EXISTS
      - CUSTOM_FIELD_VALUE_ALREADY_EXISTS
      - COULD_NOT_CREATE_RESOURCE
      - COULD_NOT_UPDATE_RESOURCE
      - COULD_NOT_DELETE_RESOURCE
      - MISSING_VERSION
      - UNSUPPORTED_VERSION
      - UNAUTHORISED
      - CUSTOMER_NOT_FOUND
      - PLATFORM_NOT_FOUND
      - PRICING_PLAN_NOT_FOUND
      - PRODUCT_NOT_FOUND
      - PRODUCT_ITEM_NOT_FOUND
      - PRICING_NOT_FOUND
      - PRICING_ITEM_NOT_FOUND
      - USER_NOT_FOUND
      - METER_NOT_FOUND
      - METER_VALUE_NOT_FOUND
      - METER_PROPERTY_NOT_FOUND
      - PRICING_ITEM_SUMMARIES_NOT_FOUND
      - MISSING_ID
      - INVALID_ID
      - MISSING_REFERENCE
      - MISSING_FIELD
      - INVALID_FIELD
      - INVALID_OPERATION
      - INTERNAL_ERROR
      - USER_NOT_ALLOWED
      - IDEMPOTENCY_CHECK_FAILED
      - INVALID_REQUEST
      title: ApiErrorCode
    RoleUpdateRequest:
      type: object
      properties:
        object_type:
          type:
          - string
          - 'null'
        id:
          type:
          - string
          - 'null'
          description: Unique identifier for the role
        name:
          type: string
          description: The name of the role
        description:
          type: string
          description: The description of the role
        entity_id:
          type:
          - string
          - 'null'
          description: When present the role is created for/by this entity
        child_role_ids:
          type: array
          items:
            type: string
          description: Child roles for this role
        child_roles:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/RoleUpdateRequestChildRolesItems'
          description: Child roles, with a max depth of 2
      title: RoleUpdateRequest
    ApiErrorType:
      type: string
      enum:
      - API_ERROR
      - INVALID_REQUEST
      title: ApiErrorType
    RoleCreateRequestChildRolesItems:
      type: object
      properties: {}
      title: RoleCreateRequestChildRolesItems
    ApiError:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/ApiErrorType'
        code:
          $ref: '#/components/schemas/ApiErrorCode'
        field:
          type:
          - string
          - 'null'
        message:
          type: string
        resource_id:
          type:
          - string
          - 'null'
        resource_type:
          oneOf:
          - $ref: '#/components/schemas/ApiErrorResourceType'
          - type: 'null'
      required:
      - type
      - code
      - message
      title: ApiError
    RoleChildRolesItems:
      type: object
      properties: {}
      title: RoleChildRolesItems
    RolePaginatedResponseWrapper:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Role'
        limit:
          type:
          - integer
          - 'null'
        page:
          type:
          - integer
          - 'null'
        total_number_of_pages:
          type:
          - integer
          - 'null'
        links:
          $ref: '#/components/schemas/PaginationLinks'
      required:
      - data
      - links
      title: RolePaginatedResponseWrapper
  securitySchemes:
    API-Key:
      type: apiKey
      in: header
      name: X-API-KEY
    JWT-Authentication:
      type: http
      scheme: bearer
